// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/ghulammuzz/misterblast/internal/storage/svc"
	"github.com/ghulammuzz/misterblast/internal/task/handler"
	"github.com/ghulammuzz/misterblast/internal/task/repo"
	"github.com/ghulammuzz/misterblast/internal/task/svc"
	"github.com/go-playground/validator/v10"
)

// Injectors from wire.go:

func InitializeTaskService(sb *sql.DB, val *validator.Validate, storageService svc.StorageService) *handler.TaskHandler {
	taskRepository := repo.NewTaskRepository(sb)
	taskService := service.NewTaskService(taskRepository, storageService)
	taskHandler := handler.NewTaskHandler(taskService, val)
	return taskHandler
}
