version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    env_file:
      - stg.env
    ports:
      - "3001:3001"
      - "3002:3002"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./deployment/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    ports:
      - "5001:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - app

networks:
  monitoring:
