// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/ghulammuzz/misterblast/internal/storage/repo"
	"github.com/ghulammuzz/misterblast/internal/storage/svc"
	"github.com/gofiber/fiber/v2"
)

// Injectors from wire.go:

func InitializeStorageService(client *fiber.Client) svc.StorageService {
	storageService := svc.NewStorageService(client)
	return storageService
}

func InitializeStorageRepository(db *sql.DB) repo.StorageRepository {
	storageRepository := repo.NewStorageRepository(db)
	return storageRepository
}
