// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	repo2 "github.com/ghulammuzz/misterblast/internal/quiz/repo"
	repo3 "github.com/ghulammuzz/misterblast/internal/task/repo"
	"github.com/ghulammuzz/misterblast/internal/user/handler"
	"github.com/ghulammuzz/misterblast/internal/user/repo"
	"github.com/ghulammuzz/misterblast/internal/user/svc"
	"github.com/go-playground/validator/v10"
)

// Injectors from wire.go:

func InitializedUserService(sb *sql.DB, val *validator.Validate) *handler.UserHandler {
	userRepository := repo.NewUserRepository(sb)
	quizRepository := repo2.NewQuizRepository(sb)
	taskRepository := repo3.NewTaskRepository(sb)
	userService := svc.NewUserService(userRepository, quizRepository, taskRepository)
	userHandler := handler.NewUserHandler(userService, val)
	return userHandler
}
