// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/ghulammuzz/misterblast/internal/quiz/handler"
	"github.com/ghulammuzz/misterblast/internal/quiz/repo"
	"github.com/ghulammuzz/misterblast/internal/quiz/svc"
	"github.com/go-playground/validator/v10"
)

// Injectors from wire.go:

func InitializedQuizService(sb *sql.DB, val *validator.Validate) *handler.QuizHandler {
	quizRepository := repo.NewQuizRepository(sb)
	quizService := svc.NewQuizService(quizRepository)
	quizHandler := handler.NewQuizHandler(quizService, val)
	return quizHandler
}
