// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/ghulammuzz/misterblast/internal/content/handler"
	"github.com/ghulammuzz/misterblast/internal/content/repo"
	"github.com/ghulammuzz/misterblast/internal/content/svc"
	"github.com/go-playground/validator/v10"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func InitializedContentService(db *sql.DB, redis2 *redis.Client, val *validator.Validate) *handler.ContentHandler {
	contentRepository := repo.NewContentRepository(db, redis2)
	contentService := svc.NewContentService(contentRepository)
	contentHandler := handler.NewContentHandler(contentService, val)
	return contentHandler
}

func InitializedAuthorService(db *sql.DB, redis2 *redis.Client, val *validator.Validate) *handler.AuthorHandler {
	authorRepository := repo.NewAuthorRepository(db, redis2)
	authorService := svc.NewAuthorService(authorRepository)
	authorHandler := handler.NewAuthorHandler(authorService, val)
	return authorHandler
}
