// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/ghulammuzz/misterblast/internal/set/handler"
	"github.com/ghulammuzz/misterblast/internal/set/repo"
	"github.com/ghulammuzz/misterblast/internal/set/svc"
	"github.com/go-playground/validator/v10"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func InitializedSetService(sb *sql.DB, redis2 *redis.Client, val *validator.Validate) *handler.SetHandler {
	setRepository := repo.NewSetRepository(sb, redis2)
	setService := svc.NewSetService(setRepository)
	setHandler := handler.NewSetHandler(setService, val)
	return setHandler
}
