name: Main CI/CD Pipeline

on:
  push:
    branches:
      - master
      
jobs:
  test:
    uses: ./.github/workflows/test.yaml

  build_push:
    needs: test
    uses: ./.github/workflows/build_push.yaml
  
  package:
    needs: build_push
    uses: ./.github/workflows/package.yaml
